site_name: Papermill Origami
site_description: A Python Library for using Noteable from papermill.
#site_url: https://???

theme:
  name: 'material'
  palette:
    - scheme: 'default'
      media: '(prefers-color-scheme: light)'
      toggle:
        icon: 'material/lightbulb'
        name: "Switch to dark mode"
    - scheme: 'slate'
      media: '(prefers-color-scheme: dark)'
      primary: 'blue'
      toggle:
        icon: 'material/lightbulb-outline'
        name: 'Switch to light mode'
  features:
    - navigation.sections

repo_name: noteable-io/papermill-origami
repo_url: https://github.com/noteable-io/papermill-origami/
edit_uri: ""

nav:
  - Introduction: 'index.md'
  - Contributing: 'contributing.md'
  - Usage:
      - QuickStart: 'quickstart.md'
  - Code Reference: reference/
  - Changes:
      - Log: 'changelog.md'

markdown_extensions:
  - pymdownx.highlight
  - deduplicate-toc
  - pymdownx.snippets
  - toc:
      permalink: "#"

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_doc_stubs.py
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [papermill_origami]
          rendering:
            show_source: true
      watch: [papermill_origami, README.md, CONTRIBUTING.md, CHANGELOG.md]
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
