name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup nox
        uses: daisylb/setup-nox@v2.1.0
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.2.0
      - name: Install dependencies
        run: |
          poetry export -f requirements.txt --extras "all" --without-hashes --with dev --output requirements.txt
          pip install -r requirements.txt
      - name: Run lint
        run: nox -s lint
